### ISSUE TITLE
PSR-0 已经废弃，是否考虑加入一段说明

### ISSUE THREAD

**Issue by lifesign** [zacao/php-developer-prepares#1]
PSR-0 (Autoloading Standard)(deprecated Use PSR-4 instead)

**Comment by zacao** [comment]
非常感谢！ 已优先完成 PSR-0 部分内容~  (commit: 3a04d05c38be44a8fec68b3bc62d3b29916a9383 )

项目刚刚启动，大量地方都还是空白待填充，欢迎继续补充 & 指正！ :)

**Comment by lifesign** [comment]
:rose:  很赞，继续关注中。
