### ISSUE TITLE
是不是考虑加一章推荐一些优秀的学习资源

### ISSUE THREAD

**Issue by lifesign** [zacao/php-developer-prepares#6]
比如前段时间比较火的 https://github.com/phptodayorg/php-must-watch

**Comment by zacao** [comment]
感谢建议！（抱歉现在才处理，这几天有急事没上线）
现在的方式是将延伸学习类资源放置在相关知识点，初衷是为了考虑阅读的连贯性，不过这样确实不便于统一查看；暂时也没有确定好的解决办法，计划在主要章节内容定型后，根据「学习资源」统一整理的情况再行决定。
欢迎给出您的建议，再次感谢！

**Comment by lifesign** [comment]
:rose:
